config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "top#index"
    resources :users
    resources :comments
  end

  root "items#index"

  resource :session, only: [:create, :destroy]

  resources :users do
    resources :items
    resources :boughts
    resources :favorites
    resources :requests
  end

  resources :items do
    get "search", on: :collection
  end

  resources :comments
  resources :requests
  resources :boughts
  resources :favorites
  resources :login, only: [:index]
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  has_secure_password
  has_many :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bought.rb
class Bought < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item, optional: true
  belongs_to :administrator, optional: true

  validates :sentence, presence: true,
    length: { maximum: 100, allow_blank: true }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_picture
  attribute :new_item_picture

  has_many :comments, dependent: :destroy
  has_many :favorite, dependent: :destroy
  has_many :request, dependent: :destroy
  has_many :bought, dependent: :destroy

  belongs_to :user
  belongs_to :status
  belongs_to :category

  validates :name, presence: true, length: { maximum: 20, allow_blank: true }
  validates :value, presence: true,
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1,
      less_than: 1000000,
      allow_blank: true
    }
  validates :detail, presence: true, length: { maximum: 500, allow_blank: true }
  validates :stock, presence: true, 
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 0,
      less_than: 100,
      allow_blank: true
    }

  class << self
    def search(name, category)
      rel = order("id")
      if name.present?
        if category == "0"
          rel = rel.where("name LIKE ?", "%#{name}%")
        else
          rel = rel.where("name LIKE ? AND category_id = ?", "%#{name}%", category)
        end
      else
        if category != "0"
          rel = rel.where("category_id = ?", category)
        end
      end
      rel
    end
  end

  before_save do
    if new_item_picture
      self.item_picture = new_item_picture
    end
  end

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/status.rb
class Status < ApplicationRecord
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :profile_picture
  attribute :new_profile_picture

  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :boughts, dependent: :destroy
  has_many :items, dependent: :destroy
  
  validates :name, presence: true,
    length: { minimum: 1, maximum: 10, allow_blank: true },
    uniqueness: { case_sensitive: false}

  validates :loginID, presence: true,
    format: { with: /\A[A-Za-z][A-Za-z0-9]*\z/, allow_blank: true },
    length: { minimum: 1, maximum: 10, allow_blank: true },
    uniqueness: { case_sensitive: false }
  
  validates :password, presence: true,
    format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])[a-zA-Z0-9]+\z/, allow_blank: true },
    length: { minimum: 3, maximum: 10, allow_blank: true }

  before_save do
    if new_profile_picture
      self.profile_picture = new_profile_picture
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def search
    @items = Item.search(params[:name_q], params[:category_q]).page(params[:page]).per(10)
    render "index"
  end

  def index
    @items = Item.order("name").page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
    @comments = Comment.where(item_id: @item.id)
  end

  def new
    @item = Item.new(user_id: current_user.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to @item, notice: "出品しました。"
    else
      render "new"
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(params[:item])
    if @item.save
      redirect_to @item, notice: "商品情報を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to :items, notice: "商品を削除しました。"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "SOSO TOWN"
    title = @page_title + " - " + title if @page_title
    title
  end

  def menu_link_to(text, path, options = {})
    content_tag :li do
      link_to_unless_current(text, path, options) do
        content_tag(:span, text)
      end
    end
  end
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/header" %>
    </header>
    <main>
      <% if flash.notice %>
        <p class = "notice"><%= flash.notice %></p>
      <% end %>

      <%= yield %>
    </main>
    <footer>
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>

app/views/shared/_footer.html.erb
<div id = "footer"><p>watawata</p></div>

app/views/shared/_header.html.erb
<h1><%= link_to "SOSO TOWN", :root %></h1>
<nav class = "menubar">
  <ul>
    <% if current_user %>
      <li><%= current_user.name + "さん" %></li>
      <li><%= menu_link_to "マイページ", user_path(current_user) %></li>
      <li><%= menu_link_to "ログアウト", :session, 
            method: :delete, data: { confirm: "ログアウトしますか？" } %></li>
    <% elsif current_admin %>
      <li><%= "管理者 " + current_admin.name + " さん" %></li>
      <li><%= menu_link_to "管理者ページ", :admin_root %></li>
      <li><%= menu_link_to "ログアウト", :session,
            method: :delete, data: { confirm: "ログアウトしますか？" } %></li>
    <% else %>
      <li><%= menu_link_to "ログイン", login_index_path %></li>
      <li><%= menu_link_to "新規会員登録", new_user_path %></li>
    <% end %>
  </ul>
</nav>