config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "top#index"
    resources :users
    resources :comments
  end

  root "items#index"

  resource :session, only: [:create, :destroy]

  resources :users do
    resources :items
    resources :boughts
    resources :favorites
    resources :requests
  end

  resources :items do
    get "search", on: :collection
  end

  resources :comments
  resources :requests
  resources :boughts
  resources :favorites
  resources :login, only: [:index]
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  has_secure_password
  has_many :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bought.rb
class Bought < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item, optional: true
  belongs_to :administrator, optional: true

  validates :sentence, presence: true,
    length: { maximum: 100, allow_blank: true }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_picture
  attribute :new_item_picture

  has_many :comments, dependent: :destroy
  has_many :favorite, dependent: :destroy
  has_many :request, dependent: :destroy
  has_many :bought, dependent: :destroy

  belongs_to :user
  belongs_to :status
  belongs_to :category

  validates :name, presence: true, length: { maximum: 20, allow_blank: true }
  validates :value, presence: true,
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1,
      less_than: 1000000,
      allow_blank: true
    }
  validates :detail, presence: true, length: { maximum: 500, allow_blank: true }
  validates :stock, presence: true, 
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 0,
      less_than: 100,
      allow_blank: true
    }

  class << self
    def search(name, category)
      rel = order("id")
      if name.present?
        if category == "0"
          rel = rel.where("name LIKE ?", "%#{name}%")
        else
          rel = rel.where("name LIKE ? AND category_id = ?", "%#{name}%", category)
        end
      else
        if category != "0"
          rel = rel.where("category_id = ?", category)
        end
      end
      rel
    end
  end

  before_save do
    if new_item_picture
      self.item_picture = new_item_picture
    end
  end

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/status.rb
class Status < ApplicationRecord
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :profile_picture
  attribute :new_profile_picture

  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :boughts, dependent: :destroy
  has_many :items, dependent: :destroy
  
  validates :name, presence: true,
    length: { minimum: 1, maximum: 10, allow_blank: true },
    uniqueness: { case_sensitive: false}

  validates :loginID, presence: true,
    format: { with: /\A[A-Za-z][A-Za-z0-9]*\z/, allow_blank: true },
    length: { minimum: 1, maximum: 10, allow_blank: true },
    uniqueness: { case_sensitive: false }
  
  validates :password, presence: true,
    format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])[a-zA-Z0-9]+\z/, allow_blank: true },
    length: { minimum: 3, maximum: 10, allow_blank: true }

  before_save do
    if new_profile_picture
      self.profile_picture = new_profile_picture
    end
  end

end

app/controllers/boughts_controller.rb
class BoughtsController < ApplicationController
  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @boughts = @user.boughts
    end
  end

  def create
    @item = Item.find(params[:item])
    @number = params[:number]
    @bought = Bought.new(user_id: current_user.id, item_id: params[:item], number: params[:number], review: 0)
    @item.stock = @item.stock - @number.to_i
    if @bought.save && @item.save
      redirect_to @item, notice: "商品を購入しました。"
    else
      redirect_to :root, notice: "エラーが発生しました。"
    end
  end

  def update
    @bought = Bought.find(params[:bought_id])
    @bought.assign_attributes(user_id: params[:user_id], item_id: params[:item_id], review: params[:review], number: params[:number])
    @user = User.find(params[:user_id])
    if @bought.save
      redirect_to [@user, :boughts], notice: "取引が完了しました。"
    else
      redirect_to [@user, :boughts], notice: "エラーが発生しました。"
    end 
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def search
    @items = Item.search(params[:name_q], params[:category_q]).page(params[:page]).per(10)
    render "index"
  end

  def index
    @items = Item.order("name").page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
    @comments = Comment.where(item_id: @item.id)
  end

  def new
    @item = Item.new(user_id: current_user.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to @item, notice: "出品しました。"
    else
      render "new"
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(params[:item])
    if @item.save
      redirect_to @item, notice: "商品情報を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to :items, notice: "商品を削除しました。"
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @comments = Comment.where(user_id: params[:id]).where.not(administrator_id: nil)
    @user = User.find(params[:id])
    @items = Item.where(user_id: params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      render "login/index", notice: "登録しました。"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(params[:user])
    if @user.save
      redirect_to @user, notice: "ユーザー情報を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :root, notice: "退会しました。"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "SOSO TOWN"
    title = @page_title + " - " + title if @page_title
    title
  end

  def menu_link_to(text, path, options = {})
    content_tag :li do
      link_to_unless_current(text, path, options) do
        content_tag(:span, text)
      end
    end
  end
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boughts/index.html.erb
<%= @page_title = @user.name + " さんの取引一覧" %>
<% if @boughts.present? %>
  <table>
    <tr>
      <th>商品名</th>
      <th>出品者</th>
      <th>個数</th>
      <th>合計金額</th>
      <th>評価</th>
    </tr>
    <% @boughts.each do |bought| %>
      <tr>
        <td><%= link_to Item.find(bought.item_id).name, Item.find(bought.item_id) %></td>
        <td><%= link_to User.find(Item.find(bought.item_id).user_id).name, User.find(Item.find(bought.item_id).user_id) %></td>
        <td><%= bought.number %> 個</td>
        <td><%= bought.number * Item.find(bought.item_id).value %> 円</td>
        <td>
          <% if bought.review != 0 %>
            <%= bought.review %>
          <% else %>
            <%= form_tag({action: :update, id: bought.id},{method: :patch}) do %>
              <% @options = [3, 2, 1] %>
              <%= select_tag 'review', options_for_select(@options) %>
              <%= hidden_field_tag :number, bought.number %>
              <%= hidden_field_tag :user_id, bought.user_id %>
              <%= hidden_field_tag :item_id, bought.item_id %>
              <%= hidden_field_tag :bought_id, bought.id %>
              <%= submit_tag "評価する" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>取引はありません。</p>
<% end %>

app/views/boughts/new.html.erb
<p><%= @test %></p>
<p>app/view/bought/new.html.erb</p>
<%= form_for @bought do |form| %>
  <% options = [] %>
  <% 1.upto(@item.stock) do |i| %>
    <% options.push i %>
  <% end %>
  個数：<%= form.select :number, options %>
<% end %>

app/views/items/_form.html.erb
<table>
  <tr>
    <th><%= form.label :new_item_picture, "商品画像" %></th>
    <td><%= form.file_field :new_item_picture %></td>
  </tr>
  <tr>
    <th><%= form.label :name, "商品名" %></th>
    <td><%= form.text_field :name, size: 15 %>・20字以内</td>
  </tr>
  <tr>
    <th><%= form.label :value, "金額" %></th>
    <td><%= form.text_field :value, size: 15 %> 円・1円〜999999円</td>
  </tr>
  <tr>
    <th><%= form.label :status_id, "状態" %></th>
    <td><%= form.select :status_id, Status.all.map{|s| [s.status, s.id]} %></td>
  </tr>
  <tr>
    <th><%= form.label :category_id, "分類" %></th>
    <td><%= form.select :category_id, Category.all.map{|c| [c.category, c.id]} %></td>
  </tr>
  <tr>
    <th><%= form.label :stock, "在庫数" %></th>
    <td><%= form.text_field :stock, size: 15 %> 個・99個以内</td>
  <tr>
    <th><%= form.label :detail, "詳細" %></th>
    <td><%= form.text_area :detail, cols: 20, rows: 5 %></td>
    <td>・500字以内</td>
  </tr>
  <div hidden>
    <%= form.label :user_id, "ユーザ" %>
    <%= form.text_field :user_id, size: 15 %>
  </div>
</table>

app/views/items/edit.html.erb
<h3><%= @page_title = @item.name + "の編集ページ" %></h3>
<%= form_for @item do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/items/index.html.erb
<% @page_title = "商品検索" %>

<% if current_user %>
  <div id = "create"><%= link_to "出品する", new_item_path %></div>
<% end %>

<div id = "search">
  <table>
    <tr>
      <th>キーワード</th>
      <th>カテゴリー</th>
      <th></th>
    </tr>
    <tr>
      <%= form_tag :search_items, method: :get, class: "search" do %>
        <td><%= text_field_tag "name_q", params[:name_q] %></td>
        <% @categories = Category.pluck(:category, :id) %>
        <% @categories.insert(0, ["選択しない", 0]) %>
        <td><%= select_tag "category_q", options_for_select(@categories, params[:category_q]) %></td>
        <td><%= submit_tag "検索" %></td>
      <% end %> 
    </tr>
  </table>
</div>

<% if @items.present? %>
  <div class = "itemlist">
    <% @items.each do |item| %>
      <div class = "item">
        <ul>
          <li id = "itempicture">
            <% if item.item_picture.attached? %>
              <%= image_tag item.item_picture.variant(resize: "100x100") %>
            <% else %>
              <%= image_tag "item.png", size: "100x100" %>
            <% end %>
          </li>
          <li><%= link_to item.name, item %></li>
          <% if item.stock > 0 %>
            <li><%= item.value %> 円</li>
          <% else %>
            <li>売り切れ</li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <%= paginate @items %>
<% else %>
  <p>出品物がありません</p>
<% end %>

app/views/items/new.html.erb
<h3><%= @page_title = "新しく出品する" %></h3>
<%= form_for @item do |form| %>
  <%= render "form", form:form %>
  <div><%= form.submit %></div>
<% end %>

app/views/items/show.html.erb
<h3><%= @page_title = @item.name + "の詳細" %></h3>
<% if current_user %>
  <% if current_user.id != @item.user_id %>
    <% if Favorite.where(user_id: current_user.id, item_id: @item.id).present? %>
      <%= form_tag({controller: :favorites, action: :destroy}, {method: :delete}) do %>
        <%= hidden_field_tag :item_id, @item.id %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= submit_tag "お気に入り解除する" %>
      <% end %>
    <% else %>
      <%= form_tag({controller: :favorites, action: :create}, {method: :post}) do %>
        <%= hidden_field_tag :item_id, @item.id %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= submit_tag "お気に入り登録する" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<table>
  <tr>
    <td>
      <% if @item.item_picture.attached? %>
        <%= image_tag @item.item_picture.variant(resize: "200x200") %>
      <% else %>
        <%= image_tag "item.png", size: "200x200" %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>出品者</th>
    <td>
      <% if current_admin %>
        <%= link_to User.find(@item.user_id).name, admin_user_path(User.find(@item.user_id)) %> さん
      <% else %>
        <%= link_to User.find(@item.user_id).name, user_path(User.find(@item.user_id)) %> さん
      <% end %>
    </td>
  <tr>
    <th>商品名</th>
    <td><%= @item.name %></td>
    <th>在庫</th>
    <td><%= @item.stock %> 個</td>
  </tr>
  <tr>
    <th>金額</th>
    <td><%= @item.value %> 円</td>
  </tr>
  <tr>
    <th>カテゴリー</th>
    <td><%= @item.category.category %></td>
    <th>状態</th>
    <td><%= @item.status.status %></td>
  </tr>
  <tr>
    <th>詳細</th>
    <td><%= @item.detail %></td>
  </tr>
</table>

<% if current_user %>
  <% if current_user.id == @item.user_id %>
    <%= link_to "編集", [:edit, @item] %> | 
    <%= link_to "削除", @item, method: :delete,
        data: { confirm: "本当に削除しますか？" } %>
  <% else %>
    <% if @item.stock > 0 %>
      <%= form_tag({controller: :boughts, action: :create},{method: :post}) do %>
        <div>
          <% @options = [] %>
          <% 1.upto(@item.stock) do |i| %>
            <% @options.push i %>
          <% end %>
          <%= select_tag 'number', options_for_select(@options) %>
          <%= hidden_field_tag :item, @item.id %>
          <%= submit_tag "購入" %>
        </div>
      <% end %>
    <% else %>
      <p>売り切れです。</p>
      <% if current_user.id == @item.user_id %>
      <% else %> 
        <%= form_tag({controller: :requests, action: :create},{method: :post}) do %>
          <div>
            <% @options = [1, 2, 3, 4, 5, 6, 7, 8, 9 , 10] %>
            <%= select_tag 'number', options_for_select(@options) %>
            <%= hidden_field_tag :item_id, @item.id %>  
            <%= submit_tag "リクエストする" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<% if current_admin %>
  <%= link_to "商品削除", @item, method: :delete,
        data: { confirm: "本当に削除しますか？" } %>
<% end %>

<% if @comments.present? %>
  <table id = "comment">
    <% @comments.each do |comment| %>
      <tr>
        <td>
          <% if comment.user_id == @item.user_id %>
            <% if User.find(comment.user_id).profile_picture.attached? %>
              <%= image_tag User.find(comment.user_id).profile_picture.variant(resize: "25x25") %>
            <% else %>
              <%= image_tag "profile.png", size: "25x25" %>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if comment.user_id == @item.user_id %>
            <% if User.find_by(id: comment.user_id) %>
              <%= link_to User.find(comment.user_id).name, User.find(comment.user_id) %>
            <% else %>
              退会済
            <% end %>
          <% end %>
        </td>
        <td><%= comment.sentence %></td>
        <td>
          <% if comment.user_id != @item.user_id %>
            <% if User.find_by(id: comment.user_id) %>
              <%= link_to User.find(comment.user_id).name, User.find(comment.user_id) %>
            <% else %>
              退会済
            <% end %>
          <% end %>
        </td>
        <td>
          <% if comment.user_id != @item.user_id %>
            <% if User.find(comment.user_id).profile_picture.attached? %>
              <%= image_tag User.find(comment.user_id).profile_picture.variant(resize: "25x25") %>
            <% else %>
              <%= image_tag "profile.png", size: "25x25" %>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if current_user || current_admin %>
            <% if current_admin || current_user.id == @item.user_id %>
              <%= form_tag({ controller: :comments, action: :destroy }, { method: :delete }) do %>
                <%= hidden_field_tag :item_id, @item.id %>
                <%= hidden_field_tag :comment_id, comment.id %>
                <%= submit_tag "削除" %>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>コメントがありません。</p>
<% end %>

<% if current_user %>
  <%= form_tag({controller: :comments, action: :create},{method: :post}) do %>
    <div>
      <%= label_tag :コメント %>
      <%= text_field_tag :sentence %>
      <%= hidden_field_tag :item_id, @item.id %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= submit_tag "送信" %>
    </div>
  <% end %>
<% end %>