config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "top#index"
    resources :users
    resources :comments
  end

  root "items#index"

  resource :session, only: [:create, :destroy]

  resources :users do
    resources :items
    resources :boughts
    resources :favorites
    resources :requests
  end

  resources :items do
    get "search", on: :collection
  end

  resources :comments
  resources :requests
  resources :boughts
  resources :favorites
  resources :login, only: [:index]
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  has_secure_password
  has_many :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bought.rb
class Bought < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item, optional: true
  belongs_to :administrator, optional: true

  validates :sentence, presence: true,
    length: { maximum: 100, allow_blank: true }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_picture
  attribute :new_item_picture

  has_many :comments, dependent: :destroy
  has_many :favorite, dependent: :destroy
  has_many :request, dependent: :destroy
  has_many :bought, dependent: :destroy

  belongs_to :user
  belongs_to :status
  belongs_to :category

  validates :name, presence: true, length: { maximum: 20, allow_blank: true }
  validates :value, presence: true,
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1,
      less_than: 1000000,
      allow_blank: true
    }
  validates :detail, presence: true, length: { maximum: 500, allow_blank: true }
  validates :stock, presence: true, 
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 0,
      less_than: 100,
      allow_blank: true
    }

  class << self
    def search(name, category)
      rel = order("id")
      if name.present?
        if category == "0"
          rel = rel.where("name LIKE ?", "%#{name}%")
        else
          rel = rel.where("name LIKE ? AND category_id = ?", "%#{name}%", category)
        end
      else
        if category != "0"
          rel = rel.where("category_id = ?", category)
        end
      end
      rel
    end
  end

  before_save do
    if new_item_picture
      self.item_picture = new_item_picture
    end
  end

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/status.rb
class Status < ApplicationRecord
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :profile_picture
  attribute :new_profile_picture

  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :boughts, dependent: :destroy
  has_many :items, dependent: :destroy
  
  validates :name, presence: true,
    length: { minimum: 1, maximum: 10, allow_blank: true },
    uniqueness: { case_sensitive: false}

  validates :loginID, presence: true,
    format: { with: /\A[A-Za-z][A-Za-z0-9]*\z/, allow_blank: true },
    length: { minimum: 1, maximum: 10, allow_blank: true },
    uniqueness: { case_sensitive: false }
  
  validates :password, presence: true,
    format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])[a-zA-Z0-9]+\z/, allow_blank: true },
    length: { minimum: 3, maximum: 10, allow_blank: true }

  before_save do
    if new_profile_picture
      self.profile_picture = new_profile_picture
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base
  def index
    @users = User.order("id")
  end

  def show
    @comments = Comment.where(user_id: params[:id]).where.not(administrator_id: nil)
    @user = User.find(params[:id])
    @items = Item.where(user_id: params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @user.destroy
    redirect_to :admin_users, notice: @user.name + " さんを退会させました。"
  end
end

app/controllers/boughts_controller.rb
class BoughtsController < ApplicationController
  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @boughts = @user.boughts
    end
  end

  def create
    @item = Item.find(params[:item])
    @number = params[:number]
    @bought = Bought.new(user_id: current_user.id, item_id: params[:item], number: params[:number], review: 0)
    @item.stock = @item.stock - @number.to_i
    if @bought.save && @item.save
      redirect_to @item, notice: "商品を購入しました。"
    else
      redirect_to :root, notice: "エラーが発生しました。"
    end
  end

  def update
    @bought = Bought.find(params[:bought_id])
    @bought.assign_attributes(user_id: params[:user_id], item_id: params[:item_id], review: params[:review], number: params[:number])
    @user = User.find(params[:user_id])
    if @bought.save
      redirect_to [@user, :boughts], notice: "取引が完了しました。"
    else
      redirect_to [@user, :boughts], notice: "エラーが発生しました。"
    end 
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def search
    @items = Item.search(params[:name_q], params[:category_q]).page(params[:page]).per(10)
    render "index"
  end

  def index
    @items = Item.order("name").page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
    @comments = Comment.where(item_id: @item.id)
  end

  def new
    @item = Item.new(user_id: current_user.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to @item, notice: "出品しました。"
    else
      render "new"
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(params[:item])
    if @item.save
      redirect_to @item, notice: "商品情報を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to :items, notice: "商品を削除しました。"
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @comments = Comment.where(user_id: params[:id]).where.not(administrator_id: nil)
    @user = User.find(params[:id])
    @items = Item.where(user_id: params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      render "login/index", notice: "登録しました。"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(params[:user])
    if @user.save
      redirect_to @user, notice: "ユーザー情報を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :root, notice: "退会しました。"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "SOSO TOWN"
    title = @page_title + " - " + title if @page_title
    title
  end

  def menu_link_to(text, path, options = {})
    content_tag :li do
      link_to_unless_current(text, path, options) do
        content_tag(:span, text)
      end
    end
  end
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<table>
  <tr>
    <th><%= form.label :name, "ユーザー名" %></th>
    <td><%= form.text_field :name, size: 15 %></td>
  </tr>
  <tr>
    <th><%= form.label :loginID, "ログインID" %></th>
    <td><%= form.text_field :loginID, size: 15 %></td>
  </tr>
  <tr>
    <th><%= form.label :password, "パスワード" %></th>
    <td><%= form.password_field :password, size: 15 %></td>
  </tr>
  <tr>
    <th><%= form.label :password_confirmation, "パスワード確認" %></th>
    <td><%= form.password_field :password_confirmation, size: 15 %></td>
  </tr>
</table>

app/views/admin/users/edit.html.erb
<h3><%= @page_title = @user.name + "の編集ページ" %></h3>
<%= form_for @user do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/admin/users/index.html.erb
<p><%= @page_title = "ユーザ一覧" %></p>
<% if @users.present? %>
  <table>
    <tr>
      <th>ユーザ名</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, [:admin, user] %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>ユーザはいません</p>
<% end %>

app/views/admin/users/new.html.erb
<h3><%= @page_title = "会員登録" %></h3>
<%= form_for @user do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit %></div>
<% end %>

app/views/admin/users/show.html.erb
<h3><%= @page_title = @user.name + " さんのページ" %></h3>

<%= form_tag({ action: :destroy }, { method: :delete }) do %>
  <%= hidden_field_tag :user_id, @user.id %>
  <%= submit_tag "#{@user.name} さんを退会させる" %>
<% end %>

<table>
  <tr>
    <td>
      <% if @user.profile_picture.attached? %>
        <%= image_tag @user.profile_picture.variant(resize: "100x100") %>
      <% else %>
        <%= image_tag "profile.png", size: "100x100" %>
      <% end %>
    </td>
    <td><%= @user.name %></td>
  </tr>
<table>

<p>評価の平均 
  <% @items = Item.where(user_id: @user.id) %>
  <% ave = 0.0 %>
  <% i = 0.0 %>
  <% if @items.present? %>
    <% @boughts = Bought.where(item_id: @items) %>
    <% if @boughts.present? %>
      <% @boughts.each do |bought| %>
        <% if bought.review > 0 %>
          <% ave += bought.review %>
          <% i += 1 %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <% if i == 0 %>
    <%= 0 %>
  <% else %>
    <%= (ave / i).round(2) %>
  <% end %>
</p>

<table>
  <tr>
    <th>管理者からのメッセージ</th>   
  </tr>
  <tr>
    <td>
      <%= form_tag(comments_path, method: :post) do %>
        <div>
          <%= text_field_tag :sentence %>
          <%= hidden_field_tag :admin_id, current_admin.id %>
          <%= hidden_field_tag :user_id, params[:id] %>
          <%= submit_tag "送信" %>
        </div>
      <% end %>
    </td>
  </tr>
  <% if @comments.present? %>
    <% @comments.each do |comment| %>
      <tr><td><%= comment.sentence %></td></tr>
    <% end %>
  <% else %>
    <tr><td>メッセージはありません。</td></tr>
  <% end %>
</table>

<p>出品物一覧</p>
<% if @items.present? %>
  <div class = "itemlist">
    <% @items.each do |item| %>
      <div class = "item">
        <ul>
          <li id = "itempicture">
            <% if item.item_picture.attached? %>
              <%= image_tag item.item_picture.variant(resize: "100x100") %>
            <% else %>
              <%= image_tag "item.png", size: "100x100" %>
            <% end %>
          </li>
          <li><%= link_to item.name, item %></li>
          <% if item.stock > 0 %>
            <li><%= item.value %> 円</li>
          <% else %>
            <li>売り切れ</li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% else %>
  <p>出品物はありません</p>
<% end %>

app/views/users/_form.html.erb
<table>
  <tr>
    <th><%= form.label :new_profile_picture, "プロフィール画像" %></th>
    <td><%= form.file_field :new_profile_picture %></td>
  </tr>
  <tr>
    <th><%= form.label :name, "ユーザー名" %></th>
    <td><%= form.text_field :name, size: 15 %>・10字以内</td>
  </tr>
  <tr>
    <th><%= form.label :loginID, "ログインID" %></th>
    <td><%= form.text_field :loginID, size: 15 %>・数英10字以内、かつ1字目は英</td>
  </tr>
  <tr>
    <th><%= form.label :password, "パスワード" %></th>
    <td><%= form.password_field :password, size: 15 %>・数大小英使用10字以内</td>
  </tr>
  <tr>
    <th><%= form.label :password_confirmation, "パスワード確認" %></th>
    <td><%= form.password_field :password_confirmation, size: 15 %></td>
  </tr>
</table>

app/views/users/show.html.erb
<% if current_user %>
  <% if current_user.id == @user.id %>
    <% @page = "マイページ" %>
  <% else %>
    <% @page = "ページ" %>
  <% end %>
<% else %>
  <% @page = "ページ" %>
<% end %>
<h3><%= @page_title = @user.name + " さんの " + @page %></h3>

<% if current_user %>
  <% if current_user.id == @user.id %>
    <p><%= link_to "マイページを編集", [:edit, @user] %> | <%= link_to "退会する", @user, method: :delete, data: { confirm: "本当に退会しますか？" } %></p>
    <p><%= link_to "お気に入り一覧", [@user, :favorites] %> | <%= link_to "取引一覧", [@user, :boughts] %> | <%= link_to "リクエスト一覧", [@user, :requests] %></p>
    <div id = "create"><%= link_to "出品する", new_item_path %></div>
  <% end %>
<% end %>

<div class = "aikon">
  <ul>
    <li>
      <% if @user.profile_picture.attached? %>
        <%= image_tag @user.profile_picture.variant(resize: "100x100") %>
      <% else %>
        <%= image_tag "profile.png", size: "100x100" %>
      <% end %>
    </li>
    <li><%= @user.name %></li>
    <li>評価の平均 
      <% @items = Item.where(user_id: @user.id) %>
      <% ave = 0.0 %>
      <% i = 0.0 %>
      <% if @items.present? %>
        <% @boughts = Bought.where(item_id: @items) %>
        <% if @boughts.present? %>
          <% @boughts.each do |bought| %>
            <% if bought.review > 0 %>
              <% ave += bought.review %>
              <% i += 1 %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <% if i == 0 %>
        <%= 0 %>
      <% else %>
        <%= (ave / i).round(2) %>
      <% end %>
    </li>
  </ul>
</div>

<% if current_user %>
  <table>
    <tr>
      <th>管理者からのメッセージ</th>
    </tr>
    <% if @comments.present? %>
      <% @comments.each do |comment| %>
        <tr><td><%= comment.sentence %></td></tr>
      <% end %>
    <% else %>
      <tr><td>メッセージはありません。</td></tr>
    <% end %>
  </table>
<% end %>

<p>出品物一覧</p>
<% if @items.present? %>
  <div class = "itemlist">
    <% @items.each do |item| %>
      <div class = "item">
        <ul>
          <li id = "itempicture">
            <% if item.item_picture.attached? %>
              <%= image_tag item.item_picture.variant(resize: "100x100") %>
            <% else %>
              <%= image_tag "item.png", size: "100x100" %>
            <% end %>
          </li>
          <li><%= link_to item.name, item %></li>
          <% if item.stock > 0 %>
            <li><%= item.value %> 円</li>
          <% else %>
            <li>売り切れ</li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% else %>
  <p>出品物はありません</p>
<% end %>